In [ ]:
import pandas as pd

# Read the Excel file into a DataFrame
file_path = 'Vehicle Population.xlsx'
# Specify the sheet name ('County' in this case)
sheet_name = 'County'

# Read the specific sheet into a DataFrame
df = pd.read_excel(file_path, sheet_name=sheet_name)

# Select only the required columns
selected_columns = ['Data Year', 'County', 'Fuel Type', 'Number of Vehicles']
df = df[selected_columns]

# Replace spaces in column names with underscores
df.columns = [col.replace(' ', '_') for col in df.columns]

# Filter rows where Fuel_Type is 'Battery Electric (BEV)'
df = df[df['Fuel_Type'] == 'Battery Electric (BEV)']

# Group by 'County' and 'Data_Year', and sum the 'Number_of_Vehicles'
grouped_df = df.groupby(['County', 'Data_Year'])['Number_of_Vehicles'].sum().reset_index()

# Print or further process the grouped DataFrame
print(grouped_df)

      County  Data_Year  Number_of_Vehicles
0    Alameda       2010                  20
1    Alameda       2011                 299
2    Alameda       2012                 555
3    Alameda       2013                1969
4    Alameda       2014                4557
..       ...        ...                 ...
693     Yuba       2018                  41
694     Yuba       2019                  84
695     Yuba       2020                 132
696     Yuba       2021                 232
697     Yuba       2022                 416

[698 rows x 3 columns]

In [ ]:
import pandas as pd

# Replace 'path_to_your_file/EV_Chargers.xlsx' with the actual path to your Excel file
file_path = 'EV_Chargers.xlsx'

sheet_name = 'Sept 2023'

# Read the specific sheet into a DataFrame
df = pd.read_excel(file_path, sheet_name=sheet_name)

# Select only the required columns
selected_columns = ['County', 'Public Level 2', 'Shared Private Level 2', 'Public DC Fast', 'Shared Private DC Fast']

# Rename columns with underscores
df.columns = [col.replace(' ', '_') for col in df.columns]
df = df[~df['County'].isin(['Total', 'Unknown'])]

# Extract counts from 'Public Level 2' and 'Shared Private Level 2' into a new column 'Level_2'
df['Level_2'] = df['Public_Level_2'] + df['Shared_Private_Level_2']

# Extract counts from 'Public DC Fast', 'Shared Private DC Fast' into a new column 'DC'
df['DC'] = df['Public_DC_Fast'] + df['Shared_Private_DC_Fast']
# Add the 'Year' column with the value '2023'
df['Year'] = 2023
# Select the final columns
final_columns = ['County', 'Year','Public_Level_2', 'Shared_Private_Level_2','Public_DC_Fast' , 'Shared_Private_DC_Fast']

# Create the final DataFrame
final_df = df[final_columns]

# Print or further process the final_df DataFrame
print(final_df)

             County  Year  Public_Level_2  Shared_Private_Level_2  \
0           Alameda  2023            1625                    2488
1            Alpine  2023              10                       0
2            Amador  2023              26                       0
3             Butte  2023              63                      55
4         Calaveras  2023               9                       0
5            Colusa  2023              16                       2
6      Contra Costa  2023             689                     758
7         Del Norte  2023              16                       1
8         El Dorado  2023             155                       4
9            Fresno  2023             483                     506
10            Glenn  2023               4                       0
11         Humboldt  2023             111                      10
12         Imperial  2023              13                      12
13             Inyo  2023               4                       5
14             Kern  2023             221                     260
15            Kings  2023              60                     247
16             Lake  2023              17                       0
17           Lassen  2023               7                       0
18      Los Angeles  2023            8213                   18893
19           Madera  2023              72                      40
20            Marin  2023             476                     509
21         Mariposa  2023              27                       0
22        Mendocino  2023             135                      20
23           Merced  2023              51                      31
24            Modoc  2023               4                       0
25             Mono  2023              19                       7
26         Monterey  2023             254                      71
27             Napa  2023             346                      54
28           Nevada  2023              43                      43
29           Orange  2023            3103                    2002
30           Placer  2023             274                     106
31           Plumas  2023               7                       0
32        Riverside  2023            1098                     219
33       Sacramento  2023            1053                     741
34       San Benito  2023              14                      10
35   San Bernardino  2023             741                     494
36        San Diego  2023            2565                    4879
37    San Francisco  2023             748                    1134
38      San Joaquin  2023             286                     280
39  San Luis Obispo  2023             394                     174
40        San Mateo  2023            2122                    2235
41    Santa Barbara  2023             280                     132
42      Santa Clara  2023            3995                   13362
43       Santa Cruz  2023             196                      97
44           Shasta  2023              85                      48
45           Sierra  2023               2                       0
46         Siskiyou  2023              20                       0
47           Solano  2023             244                     183
48           Sonoma  2023             502                     228
49       Stanislaus  2023              84                      47
50           Sutter  2023               9                       5
51           Tehama  2023              12                      46
52          Trinity  2023               4                       0
53           Tulare  2023             116                      64
54         Tuolumne  2023              32                      12
55          Ventura  2023             380                     320
56             Yolo  2023             223                     132
57             Yuba  2023              21                      51

    Public_DC_Fast  Shared_Private_DC_Fast
0              398                      37
1                0                       0
2                8                       0
3               25                       0
4               12                       0
5               18                       0
6              279                       6
7               28                       2
8               53                       1
9              285                      15
10              10                       0
11              36                       0
12              24                       1
13              44                       1
14             306                       4
15             112                       0
16               0                       0
17               8                       0
18            1906                     268
19              79                      10
20              97                       0
21              32                       0
22              59                       0
23              58                       3
24               8                       0
25              12                       0
26             154                       1
27              42                       0
28              57                       0
29             874                      22
30             137                       4
31               0                       0
32             506                      11
33             308                      20
34               5                       0
35             562                      32
36             604                      29
37             139                      34
38             148                      14
39             134                       2
40             361                      10
41             110                       2
42             698                      61
43              76                       0
44              42                       4
45               0                       0
46              48                       0
47             147                       2
48             122                      19
49              67                       3
50              16                       1
51              32                       1
52               8                       0
53              69                      23
54              10                       0
55             165                       6
56              59                       4
57               8                       0

In [ ]:
import pandas as pd

# Assuming df is your existing DataFrame
# Create a list to store the DataFrames for each year from 2024 to 2045
dfs = []

for year in range(2024, 2046):
    # Copy the existing DataFrame
    new_df = final_df.copy()

    # Set counts to 10 if they are 0
    new_df['Public_Level_2'] = new_df['Public_Level_2'].replace(0, 10)
    new_df['Shared_Private_Level_2'] = new_df['Shared_Private_Level_2'].replace(0, 10)
    new_df['Public_DC_Fast'] = new_df['Public_DC_Fast'].replace(0, 10)
    new_df['Shared_Private_DC_Fast'] = new_df['Shared_Private_DC_Fast'].replace(0, 10)

    # Update counts based on the specified percentages
    for index, row in new_df.iterrows():
        if year > 2023:  # Skip the first year as there is no previous year
            prev_year = year - 1
            county = row['County']

            # Update counts based on the specified percentages
            new_df.loc[index, 'Public_Level_2'] += int(0.15 * new_df.loc[new_df['County'] == county, 'Public_Level_2'].values[0])
            new_df.loc[index, 'Shared_Private_Level_2'] += int(0.15 * new_df.loc[new_df['County'] == county, 'Shared_Private_Level_2'].values[0])
            new_df.loc[index, 'Public_DC_Fast'] += int(0.25 * new_df.loc[new_df['County'] == county, 'Public_DC_Fast'].values[0])
            new_df.loc[index, 'Shared_Private_DC_Fast'] += int(0.25 * new_df.loc[new_df['County'] == county, 'Shared_Private_DC_Fast'].values[0])

    # Update the 'Year' column
    new_df['Year'] = year
    dfs.append(new_df)

# Concatenate all DataFrames in the list into a new DataFrame
result_df = pd.concat(dfs, ignore_index=True)

# Display the result
print(result_df)

         County  Year  Public_Level_2  Shared_Private_Level_2  Public_DC_Fast  \
0       Alameda  2024            1868                    2861             497
1        Alpine  2024              11                      11              12
2        Amador  2024              29                      11              10
3         Butte  2024              72                      63              31
4     Calaveras  2024              10                      11              15
...         ...   ...             ...                     ...             ...
1271     Tulare  2045             133                      73              86
1272   Tuolumne  2045              36                      13              12
1273    Ventura  2045             437                     368             206
1274       Yolo  2045             256                     151              73
1275       Yuba  2045              24                      58              10

      Shared_Private_DC_Fast
0                         46
1                         12
2                         12
3                         12
4                         12
...                      ...
1271                      28
1272                      12
1273                       7
1274                       5
1275                      12

[1276 rows x 6 columns]

In [ ]:
finals_df = pd.concat([final_df, result_df], axis=0, ignore_index=True)

In [ ]:
finals_df

,County,Year,Public_Level_2,Shared_Private_Level_2,Public_DC_Fast,Shared_Private_DC_Fast
0,Alameda,2023,1625,2488,398,37
1,Alpine,2023,10,0,0,0
2,Amador,2023,26,0,8,0
3,Butte,2023,63,55,25,0
4,Calaveras,2023,9,0,12,0
...,...,...,...,...,...,...
2605,Tulare,2045,133,73,86,28
2606,Tuolumne,2045,36,13,12,12
2607,Ventura,2045,437,368,206,7
2608,Yolo,2045,256,151,73,5
2609,Yuba,2045,24,58,10,12

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np


# Create a list of future years you want to predict (e.g., until 2045)
future_years = list(range(2023, 2046))

# Create a DataFrame to store the predicted values
predicted_df = pd.DataFrame(columns=['County', 'Data_Year', 'Number_of_Vehicles'])

# Iterate over each county
for county in grouped_df['County'].unique():
    # Filter data for the current county
    county_data = grouped_df[grouped_df['County'] == county]

    # Extract features (Data_Year) and target variable (Number_of_Vehicles)
    X = county_data['Data_Year'].values.reshape(-1, 1)
    y = county_data['Number_of_Vehicles'].values

    # Create a linear regression model
    model = LinearRegression()

    # Fit the model
    model.fit(X, y)

    # Predict the future values
    future_X = np.array(future_years).reshape(-1, 1)
    future_predictions = model.predict(future_X)

    # Create a DataFrame for the predicted values
    county_predicted_df = pd.DataFrame({
        'County': [county] * len(future_years),
        'Data_Year': future_years,
        'Number_of_Vehicles': future_predictions.round().astype(int)  # Round and convert to int
    })

    # Concatenate the predicted values to the overall DataFrame
    predicted_df = pd.concat([predicted_df, county_predicted_df], ignore_index=True)



# Convert Data_Year to integer
predicted_df['Data_Year'] = predicted_df['Data_Year'].astype(int)
predicted_df

       County  Data_Year Number_of_Vehicles
0     Alameda       2023              43850
1     Alameda       2024              47844
2     Alameda       2025              51838
3     Alameda       2026              55832
4     Alameda       2027              59826
...       ...        ...                ...
1375     Yuba       2041                762
1376     Yuba       2042                790
1377     Yuba       2043                817
1378     Yuba       2044                845
1379     Yuba       2045                873

[1380 rows x 3 columns]

In [ ]:
merged_df = pd.merge(final_df, predicted_df, left_on=['Year', 'County'], right_on=['Data_Year', 'County'], how='inner')

In [ ]:
merged_df.drop('Data_Year', axis=1, inplace=True)
merged_df

,County,Year,Public_Level_2,Shared_Private_Level_2,Public_DC_Fast,Shared_Private_DC_Fast,Number_of_Vehicles
0,Alameda,2023,1625,2488,398,37,43850
1,Alpine,2023,10,0,0,0,12
2,Amador,2023,26,0,8,0,165
3,Butte,2023,63,55,25,0,760
4,Calaveras,2023,9,0,12,0,203
...,...,...,...,...,...,...,...
1329,Tulare,2045,133,73,86,28,3631
1330,Tuolumne,2045,36,13,12,12,655
1331,Ventura,2045,437,368,206,7,36639
1332,Yolo,2045,256,151,73,5,7374
1333,Yuba,2045,24,58,10,12,873